### ISSUE TITLE
Error when compiling 495 driver

### ISSUE THREAD

**Issue by cheezymousehouse825** [Frogging-Family/nvidia-all#118]
My display server isn't working anymore with the latest kernel update but usually I just reinstall the driver and redo the mkinitpcio and grub cfg but for some reason this time it is saying that none of the modules exist and shows the compile log with lots of errors. It also says I'm using cc instead of gcc which I doubt is a problem since they are the same.

```
/var/lib/dkms/nvidia/495.46/build/nvidia/nv-dma.c:986: warning: "IMPORT_SGT_STUBS_NEEDED" redefined
  986 | #define IMPORT_SGT_STUBS_NEEDED 0
      | 
/var/lib/dkms/nvidia/495.46/build/nvidia/nv-dma.c:980: note: this is the location of the previous definition
  980 | #define IMPORT_SGT_STUBS_NEEDED 1
      | 
/var/lib/dkms/nvidia/495.46/build/nvidia/nv-mmap.c: In function ‘nv_encode_caching’:
/var/lib/dkms/nvidia/495.46/build/nvidia/nv-mmap.c:334:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
  334 |             if (NV_ALLOW_CACHING(memory_type))
      |                ^
/var/lib/dkms/nvidia/495.46/build/nvidia/nv-mmap.c:337:9: note: here
  337 |         default:
      |         ^~~~~~~
  CC [M]  /var/lib/dkms/nvidia/495.46/build/nvidia/nv-pat.o
/var/lib/dkms/nvidia/495.46/build/nvidia/nv-acpi.c: In function ‘nv_acpi_methods_init’:
/var/lib/dkms/nvidia/495.46/build/nvidia/nv-acpi.c:655:22: error: implicit declaration of function ‘acpi_bus_get_device’; did you mean ‘acpi_is_pnp_device’? [-Werror=implicit-function-declaration]
  655 |             retVal = acpi_bus_get_device(nvif_parent_gpu_handle, &device);
      |                      ^~~~~~~~~~~~~~~~~~~
      |                      acpi_is_pnp_device
/var/lib/dkms/nvidia/495.46/build/nvidia/nv.c: In function ‘nv_set_dma_address_size’:
/var/lib/dkms/nvidia/495.46/build/nvidia/nv.c:2891:9: error: implicit declaration of function ‘pci_set_dma_mask’; did you mean ‘ipi_send_mask’? [-Werror=implicit-function-declaration]
 2891 |         pci_set_dma_mask(nvl->pci_dev, new_mask);
      |         ^~~~~~~~~~~~~~~~
      |         ipi_send_mask
  CC [M]  /var/lib/dkms/nvidia/495.46/build/nvidia/nv-procfs.o
/var/lib/dkms/nvidia/495.46/build/nvidia/nv.c:2897:9: error: implicit declaration of function ‘pci_set_consistent_dma_mask’ [-Werror=implicit-function-declaration]
 2897 |         pci_set_consistent_dma_mask(nvl->pci_dev, new_mask);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/nvidia/495.46/build/nvidia/nv-procfs-utils.o
  CC [M]  /var/lib/dkms/nvidia/495.46/build/nvidia/nv-usermap.o
  CC [M]  /var/lib/dkms/nvidia/495.46/build/nvidia/nv-vm.o
  CC [M]  /var/lib/dkms/nvidia/495.46/build/nvidia/nv-vtophys.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/nvidia/495.46/build/nvidia/nv-acpi.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/nvidia/495.46/build/nvidia/nv.o] Error 1
make[1]: *** [Makefile:1834: /var/lib/dkms/nvidia/495.46/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.18.1-arch1-1/build'
make: *** [Makefile:80: modules] Error 2
```

**Comment by Tk-Glitch** [comment]
495 series won't work with 5.18.y kernel. Either use a 5.17.y kernel or update to 510 or 515 series.

**Comment by Jebaitedneko** [comment]
> 495 series won't work with 5.18.y kernel. Either use a 5.17.y kernel or update to 510 or 515 series.

https://github.com/Frogging-Family/nvidia-all/pull/127

should get rid of the acpi_bus_get_device error

I'll look into the rest when i can.

Saw some general bounds checking and memory allocation fixes in 515.x that could be applied to most of our proprietary drivers
