### ISSUE TITLE
Error building dkms module for 570 driver with kernel 7.1.9

### ISSUE THREAD

**Issue by kwtaylor** [Frogging-Family/nvidia-all#405]
### Same-issue check

Yes

### Kernel version

7.1.9-1-MANJARO

### NVIDIA driver version / branch

570.211.01

### Driver type

proprietary (nvidia)

### DKMS used?

YES, DKMS

### What happened?

Similar issue with 580 drivers was closed with "just use LTS kernel" but I'm not sure why this shouldn't be ultimately fixed https://github.com/Frogging-Family/nvidia-all/issues/379

```
==> dkms install --no-depmod nvidia/570.211.01 -k 7.1.9-1-MANJARO

Error! Bad return status for module build on kernel: 7.1.9-1-MANJARO (x86_64)
Consult /var/lib/dkms/nvidia/570.211.01/build/make.log for more information.

```
In dkms make.log there are many errors of the type:

```
struct vm_area_struct’ has no member named ‘__vm_flags
```

This seems to be due several changes in the kernel since 6.19/7.x: https://rglinuxtech.com/?p=3382

Here is a patch found randomly on gist, not sure if it works https://gist.github.com/louzt/1c85044d5090d19223c3f5edf426a19e

### Relevant logs

[shell-output.log.txt](https://github.com/user-attachments/files/31487568/shell-output.log.txt)

[system-info.txt](https://github.com/user-attachments/files/31487575/system-info.txt)
[customization.cfg.txt](https://github.com/user-attachments/files/31487576/customization.cfg.txt)
[prepare.log.txt](https://github.com/user-attachments/files/31487577/prepare.log.txt)

[make.log](https://github.com/user-attachments/files/31487594/make.log)

### My Favorite type(s) of frog

Red-Eyed Tree Frog (Agalychnis callidryas)

**Comment by damachine** [comment]
Thanks for the detailed information and the links!  

I’m currently unable to develop and properly test a compatibility patch for the 570 series on Linux 7.1 myself. However, you’re welcome to test the patches using nvidia-all’s user-patch mechanism. If they apply cleanly and fix the build, we can consider including them in nvidia-all.

Download the three patch files from the gist, rename them with a `.mypatch` extension, and place them in an `nvidia570-all-userpatches` directory next to the `PKGBUILD`. 

There is no need to combine them, although a single combined `.mypatch` should work as well. `_user_patches="true"` is already enabled by default in `customization.cfg`. 

Rebuild the packages and confirm the user-patch prompt when asked.  

**Please keep in mind that these are RFC patches targeting the 550 and 580 series, not 570, so they may not apply cleanly or resolve all the additional build errors.**

Cheers!
