### ISSUE TITLE
575.51.02 fails to install on linux-cachyos 6.15.0-2

### ISSUE THREAD

**Issue by z0n** [Frogging-Family/nvidia-all#293]
The DKMS build fails on Arch Linux with Kernel linux-cachyos 6.15.0-2:

```
DKMS (dkms-3.2.1) make.log for nvidia/575.51.02 for kernel 6.15.0-2-cachyos (x86_64)
Mon 26 May 23:11:02 CEST 2025

Building module(s)
# command: 'make' -j16 IGNORE_PREEMPT_RT_PRESENCE=1 NV_EXCLUDE_BUILD_MODULES='__EXCLUDE_MODULES' KERNEL_UNAME=6.15.0-2-cachyos modules LLVM=1
make[1]: Entering directory '/usr/lib/modules/6.15.0-2-cachyos/build'
make[2]: Entering directory '/var/lib/dkms/nvidia/575.51.02/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: clang version 19.1.7 (git@gitlab.archlinux.org:archlinux/packaging/packages/clang.git b536128bd29a83a26c0aafda19942995b30fc5fd)
  You are using:           clang version 19.1.7

Warning: Compiler version check failed:

The major and minor number of the compiler used to
compile the kernel:

clang version 19.1.7 (git@gitlab.archlinux.org:archlinux/packaging/packages/clang.git b536128bd29a83a26c0aafda19942995b30fc5fd), LLD 19.1.7

does not match the compiler used here:

clang version 19.1.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

It is recommended to set the CC environment variable
to the compiler that was used to compile the kernel.

To skip the test and silence this warning message, set
the IGNORE_CC_MISMATCH environment variable to "1".
However, mixing compiler versions between the kernel
and kernel modules can result in subtle bugs that are
difficult to diagnose.

*** Failed CC version check. ***

  SYMLINK nvidia/nv-kernel.o
  SYMLINK nvidia-modeset/nv-modeset-kernel.o
 CONFTEST: set_pages_uc
 CONFTEST: list_is_first
 CONFTEST: set_memory_uc
 CONFTEST: set_memory_array_uc
 CONFTEST: set_pages_array_uc
 CONFTEST: ioremap_cache
 CONFTEST: ioremap_wc
 CONFTEST: ioremap_driver_hardened
 CONFTEST: ioremap_driver_hardened_wc
 CONFTEST: ioremap_cache_shared
 CONFTEST: pci_get_domain_bus_and_slot
 CONFTEST: get_num_physpages
 CONFTEST: pde_data
 CONFTEST: xen_ioemu_inject_msi
 CONFTEST: phys_to_dma
 CONFTEST: get_dma_ops
 CONFTEST: dma_attr_macros
 CONFTEST: dma_map_page_attrs
 CONFTEST: write_cr4
 CONFTEST: of_find_node_by_phandle
 CONFTEST: of_node_to_nid
 CONFTEST: of_get_ibm_chip_id
 CONFTEST: pci_stop_and_remove_bus_device
 CONFTEST: pci_rebar_get_possible_sizes
 CONFTEST: wait_for_random_bytes
 CONFTEST: register_cpu_notifier
 CONFTEST: cpuhp_setup_state
 CONFTEST: dma_map_resource
 CONFTEST: get_backlight_device_by_name
 CONFTEST: timer_setup
 CONFTEST: pci_enable_msix_range
 CONFTEST: kernel_read_has_pointer_pos_arg
 CONFTEST: kernel_write_has_pointer_pos_arg
 CONFTEST: dma_direct_map_resource
 CONFTEST: tegra_get_platform
 CONFTEST: tegra_bpmp_send_receive
 CONFTEST: flush_cache_all
 CONFTEST: vmf_insert_pfn
 CONFTEST: jiffies_to_timespec
 CONFTEST: ktime_get_raw_ts64
 CONFTEST: ktime_get_real_ts64
 CONFTEST: full_name_hash
 CONFTEST: pci_enable_atomic_ops_to_root
 CONFTEST: vga_tryget
 CONFTEST: cc_platform_has
 CONFTEST: cc_attr_guest_sev_snp
 CONFTEST: hv_get_isolation_type
 CONFTEST: seq_read_iter
 CONFTEST: follow_pfn
 CONFTEST: ptep_get
 CONFTEST: drm_gem_object_get
 CONFTEST: drm_gem_object_put_unlocked
 CONFTEST: add_memory_driver_managed
 CONFTEST: device_property_read_u64
 CONFTEST: devm_of_platform_populate
 CONFTEST: of_dma_configure
 CONFTEST: of_property_count_elems_of_size
 CONFTEST: of_property_read_variable_u8_array
 CONFTEST: of_property_read_variable_u32_array
 CONFTEST: i2c_new_client_device
 CONFTEST: i2c_unregister_device
 CONFTEST: of_get_named_gpio
 CONFTEST: devm_gpio_request_one
 CONFTEST: gpio_direction_input
 CONFTEST: gpio_direction_output
 CONFTEST: gpio_get_value
 CONFTEST: gpio_set_value
 CONFTEST: gpio_to_irq
 CONFTEST: icc_get
 CONFTEST: devm_of_icc_get
 CONFTEST: icc_put
 CONFTEST: icc_set_bw
 CONFTEST: dma_buf_export_args
 CONFTEST: dma_buf_ops_has_kmap
 CONFTEST: dma_buf_ops_has_kmap_atomic
 CONFTEST: dma_buf_ops_has_map
 CONFTEST: dma_buf_ops_has_map_atomic
 CONFTEST: dma_buf_has_dynamic_attachment
 CONFTEST: dma_buf_attachment_has_peer2peer
 CONFTEST: dma_set_mask_and_coherent
 CONFTEST: devm_clk_bulk_get_all
 CONFTEST: get_task_ioprio
 CONFTEST: mdev_set_iommu_device
 CONFTEST: offline_and_remove_memory
 CONFTEST: stack_trace
 CONFTEST: crypto_tfm_ctx_aligned
 CONFTEST: assign_str
 CONFTEST: radix_tree_empty
 CONFTEST: radix_tree_replace_slot
 CONFTEST: cpumask_of_node
 CONFTEST: ioasid_get
 CONFTEST: mm_pasid_drop
 CONFTEST: mmget_not_zero
 CONFTEST: mmgrab
 CONFTEST: iommu_sva_bind_device_has_drvdata_arg
 CONFTEST: vm_fault_to_errno
 CONFTEST: find_next_bit_wrap
 CONFTEST: iommu_is_dma_domain
 CONFTEST: for_each_sgtable_dma_page
 CONFTEST: folio_test_swapcache
 CONFTEST: acpi_video_backlight_use_native
 CONFTEST: acpi_video_register_backlight
 CONFTEST: drm_dev_unref
 CONFTEST: drm_reinit_primary_mode_group
 CONFTEST: get_user_pages_remote
 CONFTEST: get_user_pages
 CONFTEST: pin_user_pages_remote
 CONFTEST: pin_user_pages
 CONFTEST: drm_gem_object_lookup
 CONFTEST: drm_atomic_state_ref_counting
 CONFTEST: drm_driver_has_gem_prime_res_obj
 CONFTEST: drm_atomic_helper_connector_dpms
 CONFTEST: drm_connector_funcs_have_mode_in_name
 CONFTEST: drm_connector_has_vrr_capable_property
 CONFTEST: drm_framebuffer_get
 CONFTEST: drm_dev_put
 CONFTEST: drm_format_num_planes
 CONFTEST: drm_connector_for_each_possible_encoder
 CONFTEST: drm_rotation_available
 CONFTEST: drm_vma_offset_exact_lookup_locked
 CONFTEST: nvhost_dma_fence_unpack
 CONFTEST: dma_fence_set_error
 CONFTEST: fence_set_error
 CONFTEST: sync_file_get_fence
 CONFTEST: drm_aperture_remove_conflicting_framebuffers
 CONFTEST: drm_aperture_remove_conflicting_pci_framebuffers
 CONFTEST: aperture_remove_conflicting_devices
 CONFTEST: aperture_remove_conflicting_pci_devices
 CONFTEST: drm_fbdev_generic_setup
 CONFTEST: drm_fbdev_ttm_setup
 CONFTEST: drm_client_setup
 CONFTEST: drm_connector_attach_hdr_output_metadata_property
 CONFTEST: drm_helper_crtc_enable_color_mgmt
 CONFTEST: drm_crtc_enable_color_mgmt
 CONFTEST: drm_plane_create_color_properties
 CONFTEST: drm_atomic_helper_legacy_gamma_set
 CONFTEST: vmf_insert_mixed
 CONFTEST: pfn_to_pfn_t
 CONFTEST: drm_gem_prime_mmap
 CONFTEST: is_export_symbol_gpl_of_node_to_nid
 CONFTEST: is_export_symbol_gpl_sme_active
 CONFTEST: is_export_symbol_present_swiotlb_map_sg_attrs
 CONFTEST: is_export_symbol_present_swiotlb_dma_ops
 CONFTEST: is_export_symbol_present___close_fd
 CONFTEST: is_export_symbol_present_close_fd
 CONFTEST: is_export_symbol_present_get_unused_fd
 CONFTEST: is_export_symbol_present_get_unused_fd_flags
 CONFTEST: is_export_symbol_present_nvhost_get_default_device
 CONFTEST: is_export_symbol_present_nvhost_syncpt_unit_interface_get_byte_offset
 CONFTEST: is_export_symbol_present_nvhost_syncpt_unit_interface_get_aperture
 CONFTEST: is_export_symbol_present_tegra_dce_register_ipc_client
 CONFTEST: is_export_symbol_present_tegra_dce_unregister_ipc_client
 CONFTEST: is_export_symbol_present_tegra_dce_client_ipc_send_recv
 CONFTEST: is_export_symbol_present_dram_clk_to_mc_clk
 CONFTEST: is_export_symbol_present_get_dram_num_channels
 CONFTEST: is_export_symbol_present_tegra_dram_types
 CONFTEST: is_export_symbol_present_pxm_to_node
 CONFTEST: is_export_symbol_present_screen_info
 CONFTEST: is_export_symbol_gpl_screen_info
 CONFTEST: is_export_symbol_present_i2c_bus_status
 CONFTEST: is_export_symbol_present_tegra_fuse_control_read
 CONFTEST: is_export_symbol_present_tegra_get_platform
 CONFTEST: is_export_symbol_present_pci_find_host_bridge
 CONFTEST: is_export_symbol_present_tsec_comms_send_cmd
 CONFTEST: is_export_symbol_present_tsec_comms_set_init_cb
 CONFTEST: is_export_symbol_present_tsec_comms_clear_init_cb
 CONFTEST: is_export_symbol_present_tsec_comms_alloc_mem_from_gscco
 CONFTEST: is_export_symbol_present_tsec_comms_free_gscco_mem
 CONFTEST: is_export_symbol_present_memory_block_size_bytes
 CONFTEST: crypto
 CONFTEST: crypto_akcipher_verify
 CONFTEST: is_export_symbol_present_follow_pte
 CONFTEST: follow_pte_arg_vma
 CONFTEST: is_export_symbol_present_follow_pfnmap_start
 CONFTEST: is_export_symbol_gpl_pci_ats_supported
 CONFTEST: ecc_digits_from_bytes
 CONFTEST: is_export_symbol_gpl_set_memory_encrypted
 CONFTEST: is_export_symbol_gpl_set_memory_decrypted
 CONFTEST: is_export_symbol_gpl___platform_driver_register
 CONFTEST: is_export_symbol_present___platform_driver_register
 CONFTEST: is_export_symbol_present_int_active_memcg
 CONFTEST: is_export_symbol_present_migrate_vma_setup
 CONFTEST: dma_ops
 CONFTEST: swiotlb_dma_ops
 CONFTEST: noncoherent_swiotlb_dma_ops
 CONFTEST: vm_fault_has_address
 CONFTEST: vm_insert_pfn_prot
 CONFTEST: vmf_insert_pfn_prot
 CONFTEST: vm_ops_fault_removed_vma_arg
 CONFTEST: kmem_cache_has_kobj_remove_work
 CONFTEST: sysfs_slab_unlink
 CONFTEST: proc_ops
 CONFTEST: timespec64
 CONFTEST: vmalloc_has_pgprot_t_arg
 CONFTEST: mm_has_mmap_lock
 CONFTEST: pci_channel_state
 CONFTEST: pci_dev_has_ats_enabled
 CONFTEST: remove_memory_has_nid_arg
 CONFTEST: add_memory_driver_managed_has_mhp_flags_arg
 CONFTEST: num_registered_fb
 CONFTEST: pci_driver_has_driver_managed_dma
 CONFTEST: vm_area_struct_has_const_vm_flags
 CONFTEST: memory_failure_has_trapno_arg
 CONFTEST: foll_longterm_present
 CONFTEST: bus_type_has_iommu_ops
 CONFTEST: of_property_for_each_u32_has_internal_args
 CONFTEST: platform_driver_struct_remove_returns_void
 CONFTEST: class_create_has_no_owner_arg
 CONFTEST: class_devnode_has_const_arg
 CONFTEST: mmu_notifier_ops_invalidate_range
 CONFTEST: mmu_notifier_ops_arch_invalidate_secondary_tlbs
 CONFTEST: migrate_vma_added_flags
 CONFTEST: migrate_device_range
 CONFTEST: handle_mm_fault_has_mm_arg
 CONFTEST: handle_mm_fault_has_pt_regs_arg
 CONFTEST: mempolicy_has_unified_nodes
 CONFTEST: mempolicy_has_home_node
 CONFTEST: mpol_preferred_many_present
 CONFTEST: mmu_interval_notifier
 CONFTEST: fault_flag_remote_present
 CONFTEST: sg_dma_page_iter
 CONFTEST: struct_page_has_zone_device_data
 CONFTEST: drm_bus_present
 CONFTEST: drm_bus_has_bus_type
 CONFTEST: drm_bus_has_get_irq
 CONFTEST: drm_bus_has_get_name
 CONFTEST: drm_driver_has_device_list
 CONFTEST: drm_driver_has_legacy_dev_list
 CONFTEST: drm_driver_has_set_busid
 CONFTEST: drm_crtc_state_has_connectors_changed
 CONFTEST: drm_init_function_args
 CONFTEST: drm_helper_mode_fill_fb_struct
 CONFTEST: drm_master_drop_has_from_release_arg
 CONFTEST: drm_driver_unload_has_int_return_type
 CONFTEST: drm_atomic_helper_crtc_destroy_state_has_crtc_arg
 CONFTEST: drm_atomic_helper_plane_destroy_state_has_plane_arg
 CONFTEST: drm_mode_object_find_has_file_priv_arg
 CONFTEST: dma_buf_owner
 CONFTEST: drm_connector_list_iter
 CONFTEST: drm_atomic_helper_swap_state_has_stall_arg
 CONFTEST: drm_driver_prime_flag_present
 CONFTEST: vm_fault_t
 CONFTEST: drm_gem_object_has_resv
 CONFTEST: drm_crtc_state_has_async_flip
 CONFTEST: drm_crtc_state_has_pageflip_flags
 CONFTEST: drm_crtc_state_has_vrr_enabled
 CONFTEST: drm_format_modifiers_present
 CONFTEST: drm_vma_node_is_allowed_has_tag_arg
 CONFTEST: drm_vma_offset_node_has_readonly
 CONFTEST: drm_display_mode_has_vrefresh
 CONFTEST: drm_driver_master_set_has_int_return_type
 CONFTEST: drm_driver_has_gem_free_object
 CONFTEST: drm_prime_pages_to_sg_has_drm_device_arg
 CONFTEST: drm_driver_has_gem_prime_callbacks
 CONFTEST: drm_crtc_atomic_check_has_atomic_state_arg
 CONFTEST: drm_gem_object_vmap_has_map_arg
 CONFTEST: drm_plane_atomic_check_has_atomic_state_arg
 CONFTEST: drm_device_has_pdev
 CONFTEST: drm_crtc_state_has_no_vblank
 CONFTEST: drm_mode_config_has_allow_fb_modifiers
 CONFTEST: drm_has_hdr_output_metadata
 CONFTEST: dma_resv_add_fence
 CONFTEST: dma_resv_reserve_fences
 CONFTEST: reservation_object_reserve_shared_has_num_fences_arg
 CONFTEST: drm_connector_has_override_edid
 CONFTEST: drm_master_has_leases
 CONFTEST: drm_file_get_master
 CONFTEST: drm_modeset_lock_all_end
 CONFTEST: drm_connector_lookup
 CONFTEST: drm_connector_put
 CONFTEST: drm_driver_has_dumb_destroy
 CONFTEST: fence_ops_use_64bit_seqno
 CONFTEST: drm_aperture_remove_conflicting_framebuffers_has_driver_arg
 CONFTEST: drm_aperture_remove_conflicting_framebuffers_has_no_primary_arg
 CONFTEST: drm_aperture_remove_conflicting_pci_framebuffers_has_driver_arg
 CONFTEST: drm_mode_create_dp_colorspace_property_has_supported_colorspaces_arg
 CONFTEST: drm_syncobj_features_present
 CONFTEST: drm_unlocked_ioctl_flag_present
 CONFTEST: drm_framebuffer_obj_present
 CONFTEST: drm_color_ctm_3x4_present
 CONFTEST: drm_color_lut
 CONFTEST: drm_format_info_has_is_yuv
 CONFTEST: drm_property_blob_put
 CONFTEST: drm_driver_has_gem_prime_mmap
 CONFTEST: drm_output_poll_changed
 CONFTEST: drm_driver_has_date
 CONFTEST: drm_connector_helper_funcs_mode_valid_has_const_mode_arg
 CONFTEST: dom0_kernel_present
 CONFTEST: nvidia_vgpu_kvm_build
 CONFTEST: nvidia_grid_build
 CONFTEST: nvidia_grid_csp_build
 CONFTEST: pm_runtime_available
 CONFTEST: pci_class_multimedia_hd_audio
 CONFTEST: drm_available
 CONFTEST: vfio_pci_core_available
 CONFTEST: mdev_available
 CONFTEST: cmd_uphy_display_port_init
 CONFTEST: cmd_uphy_display_port_off
 CONFTEST: memory_failure_mf_sw_simulated_defined
 CONFTEST: device_vm_build
 CONFTEST: pcie_reset_flr
 CONFTEST: module_import_ns_takes_constant
 CONFTEST: drm_atomic_available
 CONFTEST: is_export_symbol_gpl_refcount_inc
 CONFTEST: is_export_symbol_gpl_refcount_dec_and_test
 CONFTEST: drm_alpha_blending_available
 CONFTEST: is_export_symbol_present_drm_gem_prime_fd_to_handle
 CONFTEST: is_export_symbol_present_drm_gem_prime_handle_to_fd
 CONFTEST: ib_peer_memory_symbols
  CC [M]  nvidia/nv-platform.o
  CC [M]  nvidia/nv-dsi-parse-panel-props.o
  CC [M]  nvidia/nv-bpmp.o
  CC [M]  nvidia/nv-gpio.o
  CC [M]  nvidia/nv-backlight.o
  CC [M]  nvidia/nv-imp.o
  CC [M]  nvidia/nv-platform-pm.o
  CC [M]  nvidia/nv-ipc-soc.o
  CC [M]  nvidia/nv.o
  CC [M]  nvidia/nv-pci.o
nvidia/nv-dsi-parse-panel-props.c:26:10: fatal error: 'os-interface.h' file not found
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
  CC [M]  nvidia/nv-dmabuf.o
1 error generated.
nvidia/nv-bpmp.c:26:10: fatal error: 'os-interface.h' file not found
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
1 error generated.
nvidia/nv-gpio.c:26:10: fatal error: 'os-interface.h' file not found
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
1 error generated.
  CC [M]  nvidia/nv-nano-timer.o
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-dsi-parse-panel-props.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-bpmp.o] Error 1
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-gpio.o] Error 1
nvidia/nv-imp.c:26:10: fatal error: 'os-interface.h' file not found
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-imp.o] Error 1
nvidia/nv-platform-pm.c:26:10: fatal error: 'os-interface.h' file not found
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-platform-pm.o] Error 1
nvidia/nv-ipc-soc.c:26:10: fatal error: 'os-interface.h' file not found
   26 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-ipc-soc.o] Error 1
nvidia/nv-nano-timer.c:30:10: fatal error: 'os-interface.h' file not found
   30 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-nano-timer.o] Error 1
nvidia/nv.c:30:10: fatal error: 'nv-firmware.h' file not found
   30 | #include "nv-firmware.h"
      |          ^~~~~~~~~~~~~~~
nvidia/nv-platform.c:32:10: fatal error: 'nv-platform.h' file not found
   32 | #include "nv-platform.h"
      |          ^~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-platform.o] Error 1
1 error generated.
nvidia/nv-pci.c:25:10: fatal error: 'nv-pci-types.h' file not found
   25 | #include "nv-pci-types.h"
      |          ^~~~~~~~~~~~~~~~
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv.o] Error 1
1 error generated.
nvidia/nv-dmabuf.c:24:10: fatal error: 'nv-dmabuf.h' file not found
   24 | #include "nv-dmabuf.h"
      |          ^~~~~~~~~~~~~
1 error generated.
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-pci.o] Error 1
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-dmabuf.o] Error 1
nvidia/nv-backlight.c:28:10: fatal error: 'os-interface.h' file not found
   28 | #include "os-interface.h"
      |          ^~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/scripts/Makefile.build:208: nvidia/nv-backlight.o] Error 1
make[3]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/Makefile:2039: .] Error 2
make[2]: *** [/usr/lib/modules/6.15.0-2-cachyos/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/nvidia/575.51.02/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.15.0-2-cachyos/build'
make: *** [Makefile:140: modules] Error 2

# exit code: 2
# elapsed time: 00:00:18
----------------------------------------------------------------
```

**Comment by z0n** [comment]
Ah, too bad. Went for the CachyOS open drivers for now as I don't have the old kernel anymore 😅 CachyOS doesn't have package archives, does it?

Thanks for your work 🫡

**Comment by ptr1337** [comment]
> Ah, too bad. Went for the CachyOS open drivers for now as I don't have the old kernel anymore 😅 CachyOS doesn't have package archives, does it?
> 
> Thanks for your work 🫡

We do, but only for 3 versions:
https://archive.cachyos.org/archive/

**Comment by blackPantherOS** [comment]
EXTRA_CFLAGS values does not work in 6.15.x 
sed -i 's|EXTRA_CFLAGS |KBUID_CFLAGS |g' /path/to/NVIDIA-SOURCE/Kbuild
